<?php

namespace UserBundle\Repository;

/**
 * ShippingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingRepository extends \Doctrine\ORM\EntityRepository
{
}
