<?php

namespace UserBundle\Repository;

/**
 * subscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
